app = "coinbackend"
primary_region = "sin" # หรือ region ที่คุณเลือก
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
# builder = "paketobuildpacks/python:latest" # ถ้าใช้ buildpack
# ถ้าคุณใช้ Dockerfile ควรจะมี [build] แต่ไม่มี builder หรือ buildpack

[env]

[http_service]
  internal_port = 8000 # ตามที่คุณตั้งค่าใน Dockerfile
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
